### ISSUE TITLE
It's too easy to create BLEClient without BLEDevice initialized.

### ISSUE THREAD

**Issue by codepainters** [taks/esp32-nimble#145]
In my project I only use `BLEClient`. I've discovered the hard way that I need to initialize `BLEDevice`  like this:

```rust
    // this is necessary for the BLE device to get initialized
    let _ble_device = BLEDevice::take();

    let mut client = BLEClient::new();
```

If I skip `BLEDevice::take()`, it crashes later with a stack trace like this (skipped irrelevant part):
```
Backtrace: 0x42040bff:0x3fca17c0 0x42040c23:0x3fca17e0 0x420459e2:0x3fca1800 0x4200385f:0x3fca1880 0x42004257:0x3fca1990 0x420776a3:0x3fca1a70 0x420044c0:0x3fca1a90 0x4201911e:0x3fca1ab0 0x420044af:0x3fca1ae0 0x420084cf:0x3fca1b10 0x4207a07b:0x3fca1b30
0x42040bff - ble_hs_lock_nested
    at ??:??
0x42040c23 - ble_hs_lock
    at ??:??
0x420459e2 - ble_gap_connect
    at ??:??
...
```

It makes sense, that `BLEDevice::take()` performs the necessary device initialization, but perhaps it should not be possible to create `BLEDevice` instance without `BLEDevice`?

I've done a simple change to enforce exactly this:
```rust
    let ble_device = BLEDevice::take();

    let mut client = ble_device.new_client();
```

While it's an incompatible API change, obviously, maybe it's worth breaking the API?

**Comment by taks** [comment]
Thanks @codepainters

※ It seems that the error is caused not at the time of `BLEClient::new`, but at the time of `BLEClient::connect`.
