### ISSUE TITLE
Any way to get the IRK?

### ISSUE THREAD

**Issue by pierrickrouxel** [taks/esp32-nimble#149]
Hello,

I need to get the IRK of a bounded device (iOS). My goal is to use it later to filter my device.

I don't find how to do this with this library.
Is there any way to do this?

Thanks in advance.

**Comment by pierrickrouxel** [comment]
> It seems that the address of the bonded device is not a random address, but a device-specific address can be obtained.
> It should be possible to filter by this address.
Yes but I need IRK to use iPhone advertising later.

Thank you for your answer I will try `ble_store_read_local_irk`.

**Comment by pierrickrouxel** [comment]
I don't find how to use it, are you able to give me a short example?

**Comment by taks** [comment]
Sorry, I made a mistake in the function to get the IRK.
The correct function is the `ble_store_read_peer_sec` function.

It can be used as follows:
```rust
    let addr: BLEAddress = [...];

    let key = sys::ble_store_key_sec {
      peer_addr: sys::ble_addr_t {
        type_: addr.addr_type() as _,
        val: addr.as_le_bytes(),
      },
      ..Default::default()
    };

    let mut store_value = sys::ble_store_value_sec::default();
    unsafe { sys::ble_store_read_peer_sec(&key, &mut store_value); }
    ::log::info!("irk: {:?}", store_value.irk);
```
