### ISSUE TITLE
Regression in Manufacture Data from v0.7.0 -> v0.8.0

### ISSUE THREAD

**Issue by yelhouakmi** [taks/esp32-nimble#150]
Hello,

I have a temp sensor that send information in the manufacure data (Temp, Humidity, Battery level).
In v0.7.0 I can get the data without a problem and everything work. (IDF 5.2.2)
In v0.8.0/1/2 the manufacture data is not present. (IDF 5.2.2 and 5.2.3)

Tested on an esp32 and an esp32c3 (with and without « CONFIG_BT_NIMBLE_EXT_ADV=y » on the esp32c3)

The only diff on the code is the adaptation for the version bump.

If you need more info I might need some guidance. I'm not a professional embedded dev.

BTW: A big thanks for your work, it make the embedded world more accessible!!!

**Comment by yelhouakmi** [comment]
Thanks for the answer.
Here is the code that i use:
``` rust
    BLEScan::new().active_scan(true)
        .interval(100)
        .window(50)
        .start(BLEDevice::take(), 30_000, |device, data| {
            if let Some(device_name) = data.name() {
                if device_name.eq("BeeWi SmartClim") {
                    if let Some(manufacture_data) = data.manufacture_data() {
                        if manufacture_data.len() < 13 {
                            println!("Beewi data too short. Continue");
                        } else {
                            let mut sensor_data: [u8; 11] = [0; 11];
                            sensor_data.clone_from_slice(&manufacture_data[2..13]);
                            sender.send(Device::BeeWi { data: sensor_data }).unwrap();
                        }
                    }
                } else
[…]
                }
            }
            None::<()>
        })
        .await
        .unwrap();
```

Thanks for your help!

**Comment by taks** [comment]
Please try the following code.
```rust

    let mut addr = None;
    BLEScan::new()
      .active_scan(true)
      .interval(100)
      .window(50)
      .start(BLEDevice::take(), 30_000, |device, data| {
        if addr.is_none() && data.name().is_some_and(|name| name.eq("BeeWi SmartClim")) {
          addr = Some(device.addr());
        }
        if addr.is_some_and(|addr| addr == device.addr()) {
          if let Some(manufacture_data) = data.manufacture_data() {
            if manufacture_data.payload.len() < 11 {
              println!("Beewi data too short. Continue");
            } else {
              let mut sensor_data: [u8; 11] = [0; 11];
              sensor_data.clone_from_slice(&manufacture_data.payload[0..11]);
              sender.send(Device::BeeWi { data: sensor_data }).unwrap();
            }
          }
        } else {
          […]
        }

        None::<()>
      })
      .await
      .unwrap();
```

**Comment by yelhouakmi** [comment]
Just tried your code it don't work BUT it pushed me to the right direction!
The data is send without a data.name() first then I get the data object with the name included. By filtering by MAC address i retrieve the manufacture data.
I will reconstruct a double cache to keep all the data and handle these case (the case where the data is retrieve after the name is available and the case where it's the opposite).

Thanks

**Comment by yelhouakmi** [comment]
Just tried your code it don't work BUT it pushed me to the right direction!
The data is send without a device name first then I get the data with the name included.

one addr cache and a <addr, data> Map later I'm good.

Thanks!
