### ISSUE TITLE
Turn the BLE on and off

### ISSUE THREAD

**Issue by LarryMerino** [taks/esp32-nimble#26]
Is there a way to turn the BLE on and off when an event happens? When a command is sent via UART for example

**Comment by taks** [comment]
Currently, there is no function implemented to stop and start BLE again.
I will try to implement it.

**Comment by LarryMerino** [comment]
Okay, thank you very much for your response 🙏🏽
I'll be on the lookout in case there's any release of this feature.
🙌🏽
