### ISSUE TITLE
Support for esp32C6 missing

### ISSUE THREAD

**Issue by monacoprinsen** [taks/esp32-nimble#32]
Is there a plan to add support for the ESP32-C6?

**Comment by taks** [comment]
I changed to be able to build for esp32c6.
Please use the esp32c6 branch of this repository and check that it works.

For example, the example/ble_server program can be executed with the following command.
```
$ ESP_IDF_VERSION=release/v5.1.1 MCU=esp32c6 cargo espflash flash --target riscv32imac-esp-espidf --example ble_server --monitor
```
