### ISSUE TITLE
How to set adv_type?

### ISSUE THREAD

**Issue by lz1998** [taks/esp32-nimble#38]
https://docs.espressif.com/projects/esp-idf/zh_CN/release-v5.1/esp32/api-reference/bluetooth/esp_gap_ble.html#_CPPv418esp_ble_adv_type_t

**Comment by taks** [comment]
I added `BLEAdvertising.advertisement_type` function.
Please check.

**Comment by lz1998** [comment]
> I added `BLEAdvertising.advertisement_type` function. Please check.

There are 5 modes in the enum.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/esp_gap_ble.html#_CPPv418esp_ble_adv_type_t

**Comment by lz1998** [comment]
How to set the other two types?

**Comment by taks** [comment]
I have researched the two other enum.

In nimble, it appears to be set up as follows
https://github.com/espressif/esp-nimble/blob/bdf2c7588a5c7d0c16e98a168b0cf41578b119ef/nimble/host/src/ble_gap.c#L2428-L2453

I will modify the program to allow setting the relevant parameters.
