### ISSUE TITLE
Multiple connection to the BLE server

### ISSUE THREAD

**Issue by nicolasfara** [taks/esp32-nimble#4]
Hi,

I need to connect multiple clients to the BLE server. Using your example code for the server, only one client at a time is connected. Is there a way to enable a multi-client connection?

Thank you!

**Comment by taks** [comment]
By starting advertising when a connection is established, it is possible to respond to scans even while connected.
You can do it with the code below.

```rust
  let ble_device = BLEDevice::take();
  let server = ble_device.get_server();
  server.on_connect(|_| {
    ble_device.get_advertising().start();
  });
```

**Comment by taks** [comment]
By default the maximum number of connections is 3.
If you want to change the maximum number of connections, please set `CONFIG_BT_NIMBLE_MAX_CONNECTIONS` in `sdkconfig.defaults`.

**Comment by nicolasfara** [comment]
Ohh, thank you, @taks!! I'll try it out this weekend!
