### ISSUE TITLE
Indication callback

### ISSUE THREAD

**Issue by bshubenok-sigma** [taks/esp32-nimble#5]
Hi,

Is there a way to have app to know if `indicate` acknowledge received by server? Something like `on_read` callback?

**Comment by taks** [comment]
Unfortunately, I don't currently implement that way.
In the reference library, it is possible to get it with a callback called `onStatus`, so I will implement it in the same way.

**Comment by taks** [comment]
I implemented that function under the name `on_notify_tx`. (b37405332a4c2a3b59d99f2833001aa50eb80a13)

**Comment by bshubenok-sigma** [comment]
Cool!
