### ISSUE TITLE
Publish latest code to crates.io

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [taks/esp32-nimble#64]
The crates.io version is outdated and isn't compatible with the examples. I copied and pasted an example and got an error because this is different:
GitHub:
https://github.com/taks/esp32-nimble/blob/a292fe75571739017837b95bf7dd7ec0c8bec901/src/server/ble_server.rs#L47
crates.io:
https://taks.github.io/esp32-nimble/src/esp32_nimble/server/ble_server.rs.html#47
```rs
callback: impl FnMut(&mut Self, &esp_idf_sys::ble_gap_conn_desc) + Send + Sync + 'static,
```

**Comment by taks** [comment]
Version 0.5.0 has been released.

**Comment by ChocolateLoverRaj** [comment]
It works as expected now
