### ISSUE TITLE
New bug: Names that are 9 or 10 characters long result in an error when advertising is started

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [taks/esp32-nimble#86]
To reproduce: https://github.com/taks/esp32-nimble/commit/4e44350b814d76c660fe39a7ca1fbafc856bb0d9

Names I tried that don't work:
- `Bob456789`
- `Bob4567890`
- `123456789`
- `1234567890`
- `OpenSensor`

Names I tried that do work:
- `Bob`
- `12345678`
- `OpenSensor_`

I think this bug wasn't there before. I'll try to find out what commit broke this.

**Comment by ChocolateLoverRaj** [comment]
Actually I went back in past commits and I can't find a commit in 2024 that doesn't have this bug.

**Comment by taks** [comment]
This bug was present since the beginning of the implementation.
There was a bug in the calculation of the data length of service_uuid.
