### ISSUE TITLE
use Nimble for ClassicBT

### ISSUE THREAD

**Issue by CodyWangYaohui** [taks/esp32-nimble#9]
Hi,

I'm wondering whether we can use Nimble for classic bluetooth connections since until now most of the equipments are defaultly set in classic mode. I've tried the ble scan example and it works perfectly, the problem is I want it to be connectable with Raspberry pi 4b but esp32 is not seeing its mac addr anyway. Also, it cannot see my mac and iphone's BT MAC either. 

Any function calls or examples to use classic BT?

Any help would be really appreciated!

Cody

**Comment by taks** [comment]
Unfortunately, NimBLE does not support bluetooth classic.
If you use the Bluedroid Bluetooth stack, it supports bluetooth classic.

[There is also a rust wrapper that uses bluedroid, but it does not support blue classic.](https://github.com/persello/bluedroid)
There is c++ code using bluedroid. It can be used in rust if used in the same way.
- [esp-idf example](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/classic_bt)
- [arduino-esp32](https://github.com/espressif/arduino-esp32/tree/master/libraries/BluetoothSerial)
