### ISSUE TITLE
Cleanup BLEServer on BLEDevice::deinit 

### ISSUE THREAD

**Issue by mbv** [taks/esp32-nimble#99]
I’m in the process of developing an application that has the capability to establish independent BLE servers in various sections. Only one server is active at any given time. When a section ceases its server, it invokes `BLEDevice::deinit`. The expectation is that the BLEServer is reset, but in reality, `BLEDevice::deinit` only resets the started flag on the BLEServer, leaving all services and callbacks intact.

I propose the introduction of a `cleanup_server` flag to `BLEDevice::deinit` that would ensure a thorough cleanup of all elements within the BLEServer.

**Comment by taks** [comment]
I added the `BLEDevice::deinit_full` function in the [deinit_full](https://github.com/taks/esp32-nimble/tree/deinit_full) branch. 
Please check.

**Comment by mbv** [comment]
@taks thank you, it passed my tests.
